# numpy的array合并

先创建两个数列

In [1]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])
print(A,A.shape)
print(B,B.shape)

[1 1 1] (3,)
[2 2 2] (3,)


## 上下合并(vertical stack)

numpy.vstack(tup)

In [2]:
C = np.vstack((A,B))
print(C)

[[1 1 1]
 [2 2 2]]


A只是一个序列，只有3个数，没有第2个shape。而C是A,B两个序列上下合并，变为2行3列的矩阵

In [3]:
print(A.shape,C.shape)

(3,) (2, 3)


## 水平合并(horizontal stack)

numpy.hstack(tup)

In [4]:
D = np.hstack((A,B))
print(D)
print(A.shape,D.shape)

[1 1 1 2 2 2]
(3,) (6,)


因为A和B都是一个序列，所以进行左右合并后是一个有6个元素的序列

## 改变数列维度

下面的方法无法将横向数列变为竖向数列，因为数列是一维，转置不能提升维度

In [5]:
print(A.T)
print(A.T.shape)

[1 1 1]
(3,)


newaxis是numpy中的一个函数，顾名思义，就是插入新维度的意思，插入的这一维的长度为1，比如将一维数组变成二维数组，二维变成三维等

In [6]:
C = A[np.newaxis,:] #加了一个维度，变为行向量
print(C)
print(C.shape)
C = A[:,np.newaxis] #加了一个维度，变为列向量
print(C)
print(C.shape)

[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [7]:
A = np.array([1,1,1])[:,np.newaxis]
B = np.array([2,2,2])[:,np.newaxis]
D = np.hstack((A,B))
print(A)
print(B)
print(D)
print(A.shape,D.shape)

[[1]
 [1]
 [1]]
[[2]
 [2]
 [2]]
[[1 2]
 [1 2]
 [1 2]]
(3, 1) (3, 2)


## 多个array的合并

In [8]:
print(np.hstack((A,A,B)))

[[1 1 2]
 [1 1 2]
 [1 1 2]]


用axis来控制合并的方式，axis=0等同于vertical stack，axis=1等同于horizontal stack，默认axis=0

In [9]:
C = np.concatenate((A,B,B,A)) 
print(C)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
