# numpy创建array

In [1]:
import numpy as np

## 创建一维数组

括号里面填入要创建的这个array的参数，通常是列表形式，打印的结果其实和列表没有什么差别，不过中间没有了**逗号**

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


## 定义array的类型

每一种array可以定义它的类型(小数形式还是整数形式)，在创建的时候可以指定它的类型，使用**dtype = np.数据类型**或者直接用**dtype = 数据类型**

In [3]:
a = np.array([1,2,3],dtype=int)
print(a.dtype)
a = np.array([1,2,3],dtype=np.int64)
print(a.dtype)
a = np.array([1,2,3],dtype=np.float32)
print(a.dtype)
a = np.array([1,2,3],dtype=np.float64)
print(a.dtype)

int32
int64
float32
float64


通常来说位数越小所占用的空间就越小，但如果想要更精确的话，就需要位数更大的类型

## 定义二维的array(矩阵)

In [4]:
a = np.array([[1,2,3],
              [4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


## 生成全部为0的矩阵

括号里面填入行数和列数，注意行数和列数要用( )或者用[ ]括起来，在默认的情况下，zeros创建的数组元素类型是浮点型的，如果要使用其他类型，可以设置dtype参数进行声明

In [5]:
a = np.zeros([3,4],dtype=np.int16)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


## 生成全部为1的矩阵

In [6]:
a = np.ones((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 创建没有具体值的数组

In [7]:
a = np.empty((3,4))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 生成有序的数列或矩阵

In [8]:
a = np.arange(10,20,2) #类似于Python中的range
print(a)

[10 12 14 16 18]


## 改变数列的维度

使用reshpe()函数

In [9]:
a = np.arange(12)
print(a)
a = np.arange(12).reshape((3,4)) #reshape中要用()或者用[]括起来
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 生成等差数列

numpy.linspace()用于在线性空间中以均匀步长生成数字序列

In [10]:
a = np.linspace(1,10,5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]


In [11]:
a = np.linspace(1,10,6).reshape((2,3))
print(a)

[[ 1.   2.8  4.6]
 [ 6.4  8.2 10. ]]
