# numpy array分割

In [1]:
import numpy as np

先创建一个3行4列的矩阵

In [2]:
A = np.arange(12).reshape((3,4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 进行相等的分割

按列进行分割，axis=1对行操作，将每一行左右分割

In [3]:
print(np.split(A,2,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]


按行进行分割，axis=0对列进行操作，将每一列上下分割

In [4]:
print(np.split(A,3,axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## 进行不相等的分割

In [5]:
print(np.array_split(A,3,axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


## 简化的分割函数

**以下函数也只能进行相等的分割**

### 垂直分割(vertical split)

垂直(按行)将一个数组拆分为多个子数组，等价于axis=0，切割竖向线

In [6]:
print(np.vsplit(A,3))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


### 水平分割(horizontal split)

水平(按列)将数组拆分为多个子数组，等价于axis=1，切割横向线

In [7]:
print(np.hsplit(A,2))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
