# Numpy的基础运算1

先创建两个数列

In [1]:
import numpy as np
a = np.array([10,20,30,40])
b = np.arange(4)
print(a)
print(b)

[10 20 30 40]
[0 1 2 3]


## array的四则运算

进行四则运算时维度需要相同

In [2]:
print(a+b)
print(a-b)
print(a*b)

[10 21 32 43]
[10 19 28 37]
[  0  20  60 120]


## array的n次方

In [3]:
c = b**2
print(c)

[0 1 4 9]


## 三角函数运算

In [4]:
c = 10*np.sin(a)
print(c)

[-5.44021111  9.12945251 -9.88031624  7.4511316 ]


In [5]:
c = 10*np.cos(a)
print(c)
c = 10*np.tan(a)
print(c)

[-8.39071529  4.08082062  1.5425145  -6.66938062]
[  6.48360827  22.37160944 -64.05331197 -11.17214931]


## 判断array中哪些值小于某个数

In [6]:
print(b)
print(b<3)

[0 1 2 3]
[ True  True  True False]


## 矩阵的运算

In [7]:
a = np.array([[1,1],
              [0,1]])
b = np.arange(4).reshape((2,2))
print(a)
print(b)

[[1 1]
 [0 1]]
[[0 1]
 [2 3]]


## 将两个矩阵中的值逐个相乘

In [8]:
c = a*b
print(a*b)

[[0 1]
 [0 3]]


## 矩阵乘法

In [9]:
c_dot = np.dot(a,b)
print(c_dot)

[[2 4]
 [2 3]]


In [10]:
c_dot2 = a.dot(b)
print(c_dot2)

[[2 4]
 [2 3]]


## 生成随机矩阵

生成0-1的数字，参数是array的shape

In [11]:
a = np.random.random((2,4))
print(a)

[[0.77096084 0.87546529 0.97517637 0.44950762]
 [0.37530869 0.98410168 0.41939705 0.10393089]]


## 求矩阵所有元素的和

In [12]:
print(np.sum(a))

4.953848422903308


## 求矩阵所有元素的最大最小值

In [13]:
print(np.max(a))
print(np.min(a))

0.9841016788837725
0.10393089423181934


## 对矩阵的每一行求和

axis=0表示按列进行运算，axis=1表示按行进行运算

In [14]:
print(np.sum(a,axis=1))

[3.07111012 1.88273831]


## 对矩阵的每一列求和

In [15]:
print(np.sum(a,axis=0))

[1.14626953 1.85956697 1.39457341 0.55343852]


## 求矩阵每一行的最大最小值

In [16]:
print(np.min(a,axis=1))
print(np.max(a,axis=1))

[0.44950762 0.10393089]
[0.97517637 0.98410168]


## 求矩阵每一列的最大最小值

In [17]:
print(np.min(a,axis=0))
print(np.max(a,axis=0))

[0.37530869 0.87546529 0.41939705 0.10393089]
[0.77096084 0.98410168 0.97517637 0.44950762]
