# numpy copy & deep copy

In [1]:
import numpy as np

创建一个一维数组

In [2]:
a = np.arange(4)
print(a)

[0 1 2 3]


In [3]:
b = a
c = a
d = b
a[0] = 11 # 修改a中的第一个元素，默认是整型，不能改成浮点数
print(a)

[11  1  2  3]


In [4]:
print(b,c,d)

[11  1  2  3] [11  1  2  3] [11  1  2  3]


发现b,c,d也变了，因为b,c,d其实就是a

In [5]:
print(b is a,c is a,d is a) #用is判断是否是同一个对象

True True True


通过上面的输出结果可知在numpy中把array赋值给另一个变量，其实是同一个对象，这种就是**浅拷贝**，改变一个变量的值会影响到其他变量的值。进行赋值操作时，Python进行的是引用传递，两个变量指向的是同一块内存区域

In [6]:
d[1:3] = [22,33]
print(d,a,b,c)

[11 22 33  3] [11 22 33  3] [11 22 33  3] [11 22 33  3]


## 深拷贝

将被复制对象完全再复制一遍作为独立的新个体单独存在。在改变原有被复制对象时，不会对已经复制出来的新对象产生影响。copy方法可以生成一个完整的新的ndarray对象，这个ndarray对象和原始的ndarray没有任何关系

In [7]:
b = a.copy() #此时b不再关联于a，只获取a的值，deep copy
print(a,b)
a[3] = 44
print(a,b)

[11 22 33  3] [11 22 33  3]
[11 22 33 44] [11 22 33  3]
