# numpy索引

In [1]:
import numpy as np

## 获取一维数组中的某个元素

像Python中的列表一样，numpy中的array也可以索引某一个元素

In [2]:
A = np.arange(3,15)
print(A)
print(A[3])

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6


## 二维数组中的索引

### 索引某一行的元素

In [3]:
A = np.arange(3,15).reshape((3,4))
print(A)
print(A[2])

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]


### 索引某一个元素

In [4]:
print(A[1][1])
print(A[1,1])

8
8


### 索引某一行或某一列的所有元素

In [5]:
print(A[2,:])
print(A[:,1])

[11 12 13 14]
[ 4  8 12]


### 打印某一行的指定元素

In [6]:
print(A[1,1:3])

[8 9]


### 遍历每一行的元素

用for循环迭代A时，默认是迭代array中的行

In [7]:
for row in A:
    print(row)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


### 遍历每一列的元素

numpy的array中没有这样的迭代，但是可以通过矩阵的转置来实现，迭代转置后的行其实就是迭代转置前的列

In [8]:
for column in A.T:
    print(column)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


## 遍历每一个元素

A.flat返回的是一个迭代器，可以用for访问数组的每一个元素，但不能直接打印。而flatten返回的是一份数组拷贝，对拷贝所做的修改不会影响原始数组

In [9]:
print(A.flat)
print(A.flatten())
for item in A.flat:
    print(item,end=' ')

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3 4 5 6 7 8 9 10 11 12 13 14 