# numpy基础运算2

In [1]:
import numpy as np

先定义一个3行4列的矩阵

In [2]:
A = np.arange(2,14).reshape((3,4))
print(A)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


## 矩阵中最大，最小值的索引

当argmin(),argmax()无axis参数时，会将输入数组展平为一个一维数组，返回其中的最小值

In [3]:
print(np.argmin(A))
print(np.argmax(A))

0
11


## 求矩阵中所有元素的平均值

In [4]:
print(np.mean(A))
print(A.mean())

7.5
7.5


## 求矩阵中所有元素的中位数

In [5]:
print(np.median(A))

7.5


## 矩阵累加(求前缀和)

In [6]:
print(A)
print(np.cumsum(A))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]


## 一阶差分

相邻元素之差

In [7]:
print(np.diff(A))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


## 求数组中非0元素的索引

nonzero函数返回数组array中非0元素的位置(数组索引)

In [8]:
print(np.nonzero(A))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2], dtype=int64), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3], dtype=int64))


由于A是二维数组，故函数返回两个数组，第一个数组代表矩阵中非0元素的行下标，第二个数组代表矩阵中非0元素的列下标

## 矩阵排序

numpy.sort()默认每行**从小到大排序**

In [9]:
A = np.arange(14,2,-1).reshape((3,4))
print(A)
print(np.sort(A))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[11 12 13 14]
 [ 7  8  9 10]
 [ 3  4  5  6]]


## 矩阵转置

numpy.transpose(a, axes=None)用来调整多维数组的不同轴，默认情况下是对轴进行反转，因此对于二维矩阵，默认情况下是进行转置。同时也可以使用axes参数，对某几个轴进行调整

In [10]:
print(np.transpose(A))
print(A.T)

[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]
[[14 10  6]
 [13  9  5]
 [12  8  4]
 [11  7  3]]


矩阵的乘法运算中可能会经常用到转置

In [11]:
print((A.T).dot(A))

[[332 302 272 242]
 [302 275 248 221]
 [272 248 224 200]
 [242 221 200 179]]


## numpy.clip(a,a_min,a_max,out=None)

In [12]:
print(A)
print(np.clip(A,5,9))

[[14 13 12 11]
 [10  9  8  7]
 [ 6  5  4  3]]
[[9 9 9 9]
 [9 9 8 7]
 [6 5 5 5]]


clip这个函数将数组中的元素限制在a_min和a_max之间，大于a_max的就使它等于a_max，小于a_min的就使它等于a_min，其余元素的值不变